### ISSUE TITLE
SECP256K1 calculation wrong

### ISSUE THREAD

**Issue by kondranton** [BlockStoreApp/Web3Swift#116]
"v" value is calculated in a wrong way. It should be either 27 or 28.

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) please, pay attention to this issue

**Comment by 0crat** [comment]
You @kondranton[/z](https://www.0crat.com/u/kondranton) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by biboran** [comment]
@kondranton could you give an example of input for `EthTransactionBytes` which output an incorrect sequence of bytes?

Afaik `v` has [nothing to do with ecdsa](https://bitcoin.stackexchange.com/questions/38351/ecdsa-v-r-s-what-is-v?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) and is an incorrect convenience people use in web3 libraries implementation. Our implementation currently supports only [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) transaction signing scheme as you can see [here](https://github.com/BlockStoreApp/Web3Swift/blob/develop/Web3Swift/TransactionBytes/EthTransactionBytes.swift) which is `v = networkID * 2 + 35 + ecdsa.recid` instead of `v = 27 + ecdsa.recid` and a couple more arguments for an ecdsa.

I guess if we need a support for legacy signing we should declare something like `LegacyTransactionBytes` and use pre EIP-155 transaction signing scheme.

**Comment by biboran** [comment]
I believe this is not longer relevant. Here is a sample for [0x transaction signing instead](https://gist.github.com/biboran/5433f8f3937393e006fc53f41da29e29).

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
